### ISSUE TITLE
Unable to import project file, need sample for synfusion gantt

### ISSUE THREAD

**Issue by fasteddys** [SyncfusionExamples/ASPCore-Projectview-Ganttchart#2]
Hello can you please share your sample on hard import again data from project file Microsoft

**Comment by ghost** [comment]
@fasteddys  We have already discussed about import and exporting files with Microsoft Project in below blog
https://www.syncfusion.com/blogs/post/microsoft-project-files-in-javascript-gantt-chart 

Github sample: https://github.com/SyncfusionExamples/import-and-export-microsoft-project-xml-file-in-syncfusion-gantt/tree/master/GanttXMLService
